### ISSUE TITLE
Information Regarding work

### ISSUE THREAD

**Issue by mmodi97** [soadzoor/VRtualRoom#1]
Hi,

Your work is ultimate. I want to know the tool or software/ Technology by which you have developed this walk through. I am unable to understand its JS files.
Please tell I want to learn the technologies I have explored three js but i am unable to do this level.
Thanks,
Mayank

**Comment by soadzoor** [comment]
Hi,

Thank you. I used blender for the modeling, and unity for baking the lights. The JS files are only responsible for loading up the exported model in the gltf (glb) format, applying the lightmaps, and add the ability to move around. I use invisible meshes on the floor to make certain parts "walkable".

The JS file is minified, so it's no wonder you can't understand it. Unfortunately, I have plans to make a business on this code and idea, so I don't want to make it publicly available for everyone. But again: the code is really nothing special, I'm sure you can do something similar if you spend some time trying. But the most important thing is the model in this project, so you need to learn blender, or some other 3D modeling tool as well, if you'd like to create something similar. :)

Cheers,
Peter

**Comment by mmodi97** [comment]
Ok Thanks for your reply.
I really appreciate your work i did a lot of research for walking around the floor but i am unable to do . Thank you for giving me a right  direction.

Thanks,
Mayank
